### ISSUE TITLE
android.widget.TextView.setText(int) Nullpointer

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.bcomfy#54] opened 2017-08-11 02:10 UTC
<pre>
08-04 12:45:52.745 8537-8537/org.openbase.bco.bcomfy E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: org.openbase.bco.bcomfy, PID: 8537
                                                                       java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(int)' on a null object reference
                                                                           at org.openbase.bco.bcomfy.activityStart.StartActivity.changeState(StartActivity.java:178)
                                                                           at org.openbase.bco.bcomfy.activityStart.StartActivity.lambda$onCreate$0$StartActivity(StartActivity.java:90)
                                                                           at org.openbase.bco.bcomfy.activityStart.StartActivity$$Lambda$0.taskFinishedCallback(Unknown Source)
                                                                           at org.openbase.bco.bcomfy.activityStart.StartActivity$InitBcoTask.onPostExecute(StartActivity.java:369)
                                                                           at org.openbase.bco.bcomfy.activityStart.StartActivity$InitBcoTask.onPostExecute(StartActivity.java:341)
                                                                           at android.os.AsyncTask.finish(AsyncTask.java:651)
                                                                           at android.os.AsyncTask.access$500(AsyncTask.java:180)
                                                                           at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5418)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
</pre>

**Comment by jdaberkow** [comment] 2017-08-14 11:33
Duplicate of #20

**Closed as completed by jdaberkow** 2017-08-14 11:33 UTC
Labels: Bug, Duplicate
